# Generated by Django 3.0.8 on 2020-07-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
